name: Docker Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        env:
          IMAGE_NAME: my-flask-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG}
        outputs:
          image_name: ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}
          image_tag: ${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ needs.build.outputs.image_name }}:${{ needs.build.outputs.image_tag }}
            docker stop my-flask-app || true && docker rm my-flask-app || true
            docker run -d -p   5000:5000 --restart unless-stopped --name my-flask-app ${{ needs.build.outputs.image_name }}:${{ needs.build.outputs.image_tag }}
